sudo: required
dist: trusty
language: go
os:
  - linux
  - osx

install:
  - echo "overriding default travis install phase for golang"

script:
  - ruby --version
  - bundle install
  - rake

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
