language: go

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

cache:
  directories:
    - $HOME/gocache

install:
  - echo "overriding default travis install phase for golang"

script:
  - ruby --version
  - bundle install
  - rake
