language: go
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/gocache

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install gcc-4.8 g++-4.8 -y --force-yes

install:
  - echo "overriding default travis install phase for golang"

script:
  - ruby --version
  - bundle install
  - rake
